CREATE TABLE public.reservation
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name text NOT NULL,
    from_stop text NOT NULL,
    to_stop text  NOT NULL,
    arrival_time TIME NOT NULL,
	departure_time TIME NOT null,
	email text NOT NULL,
    CONSTRAINT reservation_pkey PRIMARY KEY (id)
   
)